window.TaktykiState = {
  currentMap: null,
  currentBoard: "Miejscowki",
  currentFloor: 1,
  mapImages: {
    office: "taktyki/mapy/office.png",
    vertigo: {
      1: "taktyki/mapy/vertigo.png",
      2: "taktyki/mapy/vertigo2.png",
    },
    train: "taktyki/mapy/train.png",
    italy: "taktyki/mapy/italy.png",
    mirage: "taktyki/mapy/mirage.png",
    inferno: "taktyki/mapy/inferno.png",
    ancient: "taktyki/mapy/ancient.png",
    overpass: "taktyki/mapy/overpass.png",
    nuke: "taktyki/mapy/nuke.png",
  },
  isAddingPin: false,
  pinType: null,
  tempPosition: null,
  isAddingArrow: false,
  currentArrowPin: null,
  tempArrowEnd: null,
  isFreeDrawing: false,
  drawMode: "pen",
  lineDrawStart: null,
  freeDrawColor: "#32d583",
  freeDrawDashed: false,
  tempStrokePoints: [],
  editingPin: null,
  playerColors: {
    Dziadek: "#ff9800",
    Matka: "#4caf50",
    Ojciec: "#2196f3",
    Wujek: "#ffeb3b",
    Synek: "#9c27b0",
    Kowal: "#4fc3f7",
    Telemans: "#111111",
    Gruby: "#f44336",
  },
};
